name: cursor_ai_project_web
description: A new Flutter project for desktop web that gamifies wellness activities.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0" # Dart SDKのバージョンを指定
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  json_annotation: ^4.0.1
  provider: ^6.0.0
  flutter_dotenv: ^5.0.2
  oauth2: ^2.0.0
  flutter_secure_storage: ^4.2.0
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  json_serializable: ^6.0.1
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

# Custom fonts and images are assumed to be used in the project, hence included in the assets.
